# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 13.0

# Window
remember_window_size yes
confirm_os_window_close 0
os_window_state maximized

background_opacity 0.5
background_blur 32

# Padding
window_padding_width 8

# Cursor
cursor_shape beam
cursor_blink_interval 0.5
cursor #f5e0dc
cursor_text_color #11111b

# Scrollback
scrollback_lines 10000

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# General
detect_urls yes
tab_bar_edge top
tab_bar_style powerline
shell fish
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Basic Colors
foreground #cdd6f4
background #11111b
selection_foreground #11111b
selection_background #f5e0dc
